// <auto-generated />
namespace EveOnlineFittingAssistant_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class refactorfix1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactorfix1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110211810041_refactor fix 1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
