// <auto-generated />
namespace EveOnlineFittingAssistant_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class thing1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thing1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110211515143_thing1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
